---
title: "Living with gentle giants"
date: 2018-08-07
---

title: Living with gentle giants
author: Pooja Adiseshu
email: pa@emory.edu
description: > # this means to ignore newlines until "baseurl:"
I love elephants and want to live with them in the wild and learn more about them.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
